version: '2.4'

services:

  rda-registry:
    platform: linux/amd64
    container_name: rda-registry
    image: minhd/rda-registry:r42
    volumes:
      - ./rda-registry/bin/fix-permissions.sh:/bin/fix-permissions.sh
      - ./rda-registry/bin/populate-concepts-collection.sh:/bin/populate-concepts-collection.sh
      - ./rda-registry/conf/concepts.json:/tmp/concepts.json
      - ./rda-registry/conf/.env.rda-registry:/opt/apps/registry/current/.env
      - /etc/localtime:/etc/localtime
    ports:
      - "80:80"

  mysql:
    platform: linux/amd64
    container_name: mysql
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbs_registry
      MYSQL_USER: webuser
      MYSQL_PASSWORD: webuser

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4.10
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
      ZOO_4LW_COMMANDS_WHITELIST: mntr, conf, ruok

  solr:
    container_name: solr
    image: solr:8.11.1
    depends_on:
      - zookeeper
    volumes:
      - ./solr/conf/:/confs:rw
      - ./solr/conf/files/jts-core-1.15.0.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/jts-core-1.15.0.jar
      - ./solr/bin/create-collections.sh:/bin/create-collections.sh
    environment:
      - ZK_HOST=zookeeper:2181
    ports:
      - "8983:8983"

  neo4j:
    platform: linux/amd64
    container_name: neo4j
    image: neo4j:3.5
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/minhd
      # - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true

  redis:
    container_name: redis
    image: redis:3.2
    ports:
      - "6379:6379"
